#ifndef _GLOBAL_H
#define _GLOBAL_H

#define NUM_SYMBOL_BASIC 6
#define NUM_SYMBOL_INTERMEDIATE 8
#define NUM_SYMBOL_ADVANCED 10
#define CODE_LENGTH_BASIC 3
#define CODE_LENGTH_INTERMEDIATE 4 // stesso valore di CODE_LENGTH_ADVANCED
#define NUM_ATTEMPTS_BASIC 20
#define NUM_ATTEMPTS_INTERMEDIATE 15
#define NUM_ATTEMPTS_ADVANCED 9
#define START_NUMBERS_ASCII 48
#define NUM_RESULTS 2
#define MAX_DIM_ID 4
#define TRUE 1
#define FALSE 0

#endif
